#! /bin/bash

if test $# -lt 2 ; then
	echo "Usage: $0 files"
	exit 0
fi

files=($@)
num_done=0

echo "#! /usr/bin/gnuplot -persist" > draw_compare
chmod u+x draw_compare
for i in ${files[*]} ; do
	if test $num_done -eq 0 ; then
		echo -n "plot \"$i\" using 1:2 w l" >> draw_compare
	else
		echo -n ", \"$i\" using 1:2 w l" >> draw_compare
	fi
	num_done=$((num_done+1))
done

./draw_compare


